name: "Gulp Build"
description: "Build a project using Gulp"

inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "20.x"
  gulp-build-task:
    description: "Task to run from the Gulp file"
    required: true
    default: "default"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install NPM dependencies
      shell: bash
      run: npm ci

    - name: Install Gulp globally
      shell: bash
      run: npm install -g gulp-cli

    - name: Run Gulp build task
      shell: bash
      run: gulp ${{ inputs.gulp-build-task }}
