name: Grogwood.com

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # AWS
  AWS_S3_BUCKET_NAME: ${{ vars.AWS_S3_BUCKET_NAME }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  # Build settings
  NODE_VERSION: 20.x
  GULP_BUILD_TASK: prod
  GULP_BUILD_PATH: dist
  # FILE PATHS
  INDEX_FILE_PATH: dist/index.html
  CSS_FILE_PATH: dist/assets/css/styles.min.css
  JS_FILE_PATH: dist/assets/js/scripts.min.css

jobs:
  build:
    name: Build [ Gulp ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build project
        uses: scottyrichardson/github-actions/.github/actions/gulp-build@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          gulp-build-task: ${{ env.GULP_BUILD_TASK }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GULP_BUILD_PATH }}
          path: ${{ env.GULP_BUILD_PATH }}
          retention-days: 7

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GULP_BUILD_PATH }}
          path: ${{ env.GULP_BUILD_PATH }}

      - name: Validate index file
        uses: scottyrichardson/github-actions/.github/actions/validate-file@v1
        with:
          file-path: ${{ env.INDEX_FILE_PATH }}

      - name: Validate CSS file
        uses: scottyrichardson/github-actions/.github/actions/validate-file@v1
        with:
          file-path: ${{ env.CSS_FILE_PATH }}

      - name: Validate Javascript file
        uses: scottyrichardson/github-actions/.github/actions/validate-file@v1
        with:
          file-path: ${{ env.CSS_FILE_PATH }}

      - name: Validate HTML
        uses: scottyrichardson/github-actions/.github/actions/validate-html@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          source-path: ${{ env.GULP_BUILD_PATH }}

  deploy:
    name: Deploy [ AWS ]
    runs-on: ubuntu-latest
    needs: [build, validate]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GULP_BUILD_PATH }}
          path: ${{ env.GULP_BUILD_PATH }}

      - name: Deploy artifact to AWS S3 bucket
        uses: scottyrichardson/github-actions/.github/actions/aws-s3-upload@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GROGWOOD_DEPLOYER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GROGWOOD_DEPLOYER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          source-path: ${{ env.GULP_BUILD_PATH }}

  invalidate-cache:
    name: Invalidate Cache [ CloudFront ]
    runs-on: ubuntu-latest
    needs: [build, validate, deploy]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Invalidate CloudFront cache
        uses: scottyrichardson/github-actions/.github/actions/aws-cloudfront-invalidation@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GROGWOOD_DEPLOYER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GROGWOOD_DEPLOYER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cloudfront-distribution-id: ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          cloudfront-invalidation-path: /*
